prod:
  class_index:
    - "conventional tillage (ploughing)"
    - "conservation tillage"
    - "autumn crop"
    - "grass"
    - "stubble (no tillage)"
    - "stubble with companion crop"


  pipeline:
    do_anonymize: true
    cache_index_root: ./cache
    do_compile_stan_models: false
    use_cached_densities: false
    suppress_summary: false
    use_matlab: false
  pixel_sampler:
    output_dir: ./data
    raster_files:
      s1_mosaic:
        file_name: /var/data/3/work/sar_veg/s1m_grd_20180411-20180421_vh_vv.tif
        band_index:
          - Intensity_VH
          - Intensity_VV
      s2_ndti_ndvi:
        file_name: /var/data/3/work/sar_veg/S2A_MSIL2A_201804_mosaic_T34VFM_T34VEN_T34VFN_cld+snw+ndti+ndvi.tif
        band_index:
          - B2
          - B3
          - B4
          - p_cld
          - p_snw
          - ndti
          - ndvi

    shapefile_root: /var/data/3/work/sar_veg/references
    class_shapefiles:
      - target-reference0-2018.shp
      - target-reference1-2018.shp
      - target-reference2-2018.shp
      - target-reference3-2018.shp
      - target-reference4-2018.shp
      - target-reference5-2018.shp
